// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh35UGB2dMu7XgChiPGWjYLqGWQCCli6c',
    appId: '1:156019165379:web:a7fe0a2bfb5e961289fa76',
    messagingSenderId: '156019165379',
    projectId: 'health-compass-12e1c',
    authDomain: 'health-compass-12e1c.firebaseapp.com',
    storageBucket: 'health-compass-12e1c.firebasestorage.app',
    measurementId: 'G-HTRENEQ17J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPxFjafXAh7Lin147jSNW_e5Xj1eUrkoA',
    appId: '1:156019165379:android:a8057619ddd099a189fa76',
    messagingSenderId: '156019165379',
    projectId: 'health-compass-12e1c',
    storageBucket: 'health-compass-12e1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqsIIOk2aIJk2CmXFvHT1RcdFBrnzzzqY',
    appId: '1:156019165379:ios:f4fdd6a97ba7ae2e89fa76',
    messagingSenderId: '156019165379',
    projectId: 'health-compass-12e1c',
    storageBucket: 'health-compass-12e1c.firebasestorage.app',
    iosBundleId: 'com.example.healthCompass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqsIIOk2aIJk2CmXFvHT1RcdFBrnzzzqY',
    appId: '1:156019165379:ios:f4fdd6a97ba7ae2e89fa76',
    messagingSenderId: '156019165379',
    projectId: 'health-compass-12e1c',
    storageBucket: 'health-compass-12e1c.firebasestorage.app',
    iosBundleId: 'com.example.healthCompass',
  );
}
